### PR TITLE
[33477] don't overwrite sshd configuration

### PR DESCRIPTION
**Pull request by scottminter**

### CODE REVIEW

**Comment by amikheychik** [comment]
Overriding SSHD should remain an option, just disabled by default.

**Comment by davidbeauchamp** [comment]
Unless we want to make a separate module for XTAU for our own cloud/ops team then we should never be touching SSH. XTAU is a toolkit to manage our stack, not the server itself, and xTuple has nothing to do with SSH.

**Comment by amikheychik** [comment]
@davidbeauchamp we do need such a module, because we offer a "cloud" solution, hence we configure servers from scratch.

**Comment by amikheychik** [comment]
@davidbeauchamp not to mention, I've been many times told that one of the reason to have visual user interface for xTAU is that people with any level of knowledge would be able to install the stack. "Any level of knowledge" would suggest that we have to think about security for such people.

**Comment by amikheychik** [comment]
@gilmoskowitz that's why I said it should be an option (e.g. turned off by default)

**Pull request merged**
