### PR TITLE
Properly initialize mobile client version variable

### PR DESCRIPTION
**Pull request by paladinlogic**
### Summary
Every time I would try to use xTAU in automated mode, it would upgrade the instance to 4.10b2. I found out this was because variable used in the 'git checkout' command is never instantiated in the function it is used, but rather in a function that calls that function.

### What I did:
1. Renamed MWCSTRING to MWCREFSPEC, as that's what it is used for.
2. Passing MWCREFSPEC to install_mwc as $2 (made the most sense to me anyway)
   * Adjusted arg references in install_mwc accordingly

### CODE REVIEW

**Comment by paladinlogic** [comment]
@gilmoskowitz @davidbeauchamp Here is what I have already tested to be merge in. The xvfb changes are only partially tested. I also resolved the merge conflict.

**Comment by gilmoskowitz** [comment]
+1

**Comment by davidbeauchamp** [comment]
Thank you. Will you submit another PR with the xvfb startup script again? I will add in the systemd service unit with it --

**Comment by gilmoskowitz** [comment]
see issue #27894

**Pull request merged**
