### PR TITLE
tweaked update message

### PR DESCRIPTION
**Pull request by bixwilson**

### CODE REVIEW

**Comment by xtuple-ci-user** [comment]
Can one of the admins verify this patch?

**Comment by davidbeauchamp** [comment]
jenkins - retest this please

**Comment by davidbeauchamp** [comment]
jenkins - retest this please

**Comment by davidbeauchamp** [comment]
jenkins - retest this please.

**Comment by bixwilson** [comment]
jenkins - retest this please

**Comment by davidbeauchamp** [comment]
jenkins - retest this please

**Pull request merged**
